---
- name: Install Docker
  hosts: geostack
  become: true
  roles:
    - docker

- name: Handle Dataviewer
  hosts: geostack
  become: true
  roles:
    - dataviewer

- name: Deploy GeoStack
  hosts: geostack
  become: true
  roles:
    - geostack