name: Deploy GeoStack

on:
  workflow_dispatch:
  # push:
  #   branches: [ "devel" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
    steps:
      - name: Checkout Infrastructure Repo
        uses: actions/checkout@v4

      - name: Checkout static site
        uses: actions/checkout@v4
        with:
          repository: wolsk1/data-viewer
          token: ${{ secrets.DATA_VIEWER_REPO_TOKEN }}
          path: dataviewer-src

      - name: Copy static site into Ansible role
        run: |
          rm -rf ansible/roles/dataviewer/files/dataviewer-src
          cp -r dataviewer-src ansible/roles/dataviewer/files/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${DEPLOY_HOST}" >> ~/.ssh/known_hosts

      - name: Create dynamic inventory
        run: |
          mkdir -p ansible/inventory
          cat > ansible/inventory/hosts <<EOF
          [geostack]
          ${DEPLOY_HOST} ansible_user=${{ secrets.SSH_USERNAME }} ansible_ssh_private_key_file=~/.ssh/id_ed25519
          EOF
          cat ansible/inventory/hosts
      
      - name: Create SSL Mapping directory
        run: |
            sudo mkdir -p /opt/ssl/letsencrypt        # certs and renewal configs
            sudo mkdir -p /opt/ssl/lib                # certbot state
            sudo mkdir -p /opt/ssl/www/.well-known/acme-challenge
            sudo chown -R $(whoami):$(whoami) /opt/ssl

      - name: GeoStack Playbook Executions
        run: ansible-playbook -i ansible/inventory/hosts ansible/site.yml \
            -e "geoserver_admin_user=$GEOSERVER_ADMIN_USER \
                geoserver_admin_password=$GEOSERVER_ADMIN_PASSWORD \
                postgres_user=$POSTGRES_USER \
                postgres_password=$POSTGRES_PASSWORD \
                postgres_db=$POSTGRES_DB
                geostack_domain=$GEOSTACK_DOMAIN"